// flow-typed signature: e03bcc54fde508d35b92127ff96a755d
// flow-typed version: <<STUB>>/react-beautiful-dnd_v^2.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-beautiful-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-beautiful-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/jest.config' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-diff-to-jump-to-next-index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-drag-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-new-home-client-offset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/hook-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/is-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/jump-to-next-index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/log-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/selectors' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/dimension-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-window-scroll-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/moveable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/moveable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-new-home-client-offset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/hook-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/jump-to-next-index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/log-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/selectors' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/dimension-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-window-scroll-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/1-single-vertical-list-story' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/2-single-horizontal-story' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/3-complex-vertical-list-story' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/4-board-story' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/board/board' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/board/column' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/constants' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/data' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/horizontal/author-app' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/horizontal/author-item' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/horizontal/author-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/horizontal/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/primatives/quote-item' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/reorder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical-grouped/quote-app' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical-nested/quote-app' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical-nested/quote-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical-nested/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical/quote-app' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/stories/src/vertical/quote-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/setup' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/integration/hooks-integration.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/create-store.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/dimension.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/get-drag-impact.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/get-draggables-inside-droppable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/get-droppable-over.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/get-new-home-client-offset.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/hook-middleware.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/jump-to-next-index.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/state/position.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/connected-draggable-dimension-publisher.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/connected-draggable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/connected-droppable-dimension-publisher.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/connected-droppable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/drag-drop-context.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/drag-handle.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/moveable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/unconnected-draggable-dimension-publisher.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/unconnected-draggable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/unconnected-droppable-dimension-publisher.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/unit/view/unconnected-droppable.spec' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/utils/get-client-rect' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/utils/get-context-options' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/utils/set-window-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/test/utils/user-input-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x'>;
}
declare module 'react-beautiful-dnd/jest.config.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/jest.config'>;
}
declare module 'react-beautiful-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/index'>;
}
declare module 'react-beautiful-dnd/lib/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/action-creators'>;
}
declare module 'react-beautiful-dnd/lib/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/axis'>;
}
declare module 'react-beautiful-dnd/lib/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/create-store'>;
}
declare module 'react-beautiful-dnd/lib/state/dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/dimension'>;
}
declare module 'react-beautiful-dnd/lib/state/get-diff-to-jump-to-next-index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-diff-to-jump-to-next-index'>;
}
declare module 'react-beautiful-dnd/lib/state/get-drag-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-drag-impact'>;
}
declare module 'react-beautiful-dnd/lib/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/lib/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/lib/state/get-new-home-client-offset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-new-home-client-offset'>;
}
declare module 'react-beautiful-dnd/lib/state/hook-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/hook-middleware'>;
}
declare module 'react-beautiful-dnd/lib/state/is-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/is-inside-droppable'>;
}
declare module 'react-beautiful-dnd/lib/state/jump-to-next-index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/jump-to-next-index'>;
}
declare module 'react-beautiful-dnd/lib/state/log-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/log-middleware'>;
}
declare module 'react-beautiful-dnd/lib/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/no-impact'>;
}
declare module 'react-beautiful-dnd/lib/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/position'>;
}
declare module 'react-beautiful-dnd/lib/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/reducer'>;
}
declare module 'react-beautiful-dnd/lib/state/selectors.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/selectors'>;
}
declare module 'react-beautiful-dnd/lib/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/types'>;
}
declare module 'react-beautiful-dnd/lib/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/animation'>;
}
declare module 'react-beautiful-dnd/lib/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/context-keys'>;
}
declare module 'react-beautiful-dnd/lib/view/dimension-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/dimension-types'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/placeholder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/placeholder'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/get-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-center-position'>;
}
declare module 'react-beautiful-dnd/lib/view/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/lib/view/get-window-scroll-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-window-scroll-position'>;
}
declare module 'react-beautiful-dnd/lib/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/key-codes'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/moveable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/moveable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/moveable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/moveable'>;
}
declare module 'react-beautiful-dnd/src/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/index'>;
}
declare module 'react-beautiful-dnd/src/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/action-creators'>;
}
declare module 'react-beautiful-dnd/src/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/axis'>;
}
declare module 'react-beautiful-dnd/src/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/create-store'>;
}
declare module 'react-beautiful-dnd/src/state/dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact'>;
}
declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/src/state/get-new-home-client-offset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-new-home-client-offset'>;
}
declare module 'react-beautiful-dnd/src/state/hook-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/hook-middleware'>;
}
declare module 'react-beautiful-dnd/src/state/is-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-inside-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/jump-to-next-index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/jump-to-next-index'>;
}
declare module 'react-beautiful-dnd/src/state/log-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/log-middleware'>;
}
declare module 'react-beautiful-dnd/src/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/no-impact'>;
}
declare module 'react-beautiful-dnd/src/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/position'>;
}
declare module 'react-beautiful-dnd/src/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/reducer'>;
}
declare module 'react-beautiful-dnd/src/state/selectors.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/selectors'>;
}
declare module 'react-beautiful-dnd/src/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/types'>;
}
declare module 'react-beautiful-dnd/src/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/animation'>;
}
declare module 'react-beautiful-dnd/src/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/context-keys'>;
}
declare module 'react-beautiful-dnd/src/view/dimension-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/dimension-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/placeholder.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/placeholder'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/src/view/get-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-center-position'>;
}
declare module 'react-beautiful-dnd/src/view/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/src/view/get-window-scroll-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-window-scroll-position'>;
}
declare module 'react-beautiful-dnd/src/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/key-codes'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/index'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable-types'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable'>;
}
declare module 'react-beautiful-dnd/stories/1-single-vertical-list-story.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/1-single-vertical-list-story'>;
}
declare module 'react-beautiful-dnd/stories/2-single-horizontal-story.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/2-single-horizontal-story'>;
}
declare module 'react-beautiful-dnd/stories/3-complex-vertical-list-story.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/3-complex-vertical-list-story'>;
}
declare module 'react-beautiful-dnd/stories/4-board-story.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/4-board-story'>;
}
declare module 'react-beautiful-dnd/stories/src/board/board.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/board/board'>;
}
declare module 'react-beautiful-dnd/stories/src/board/column.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/board/column'>;
}
declare module 'react-beautiful-dnd/stories/src/constants.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/constants'>;
}
declare module 'react-beautiful-dnd/stories/src/data.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/data'>;
}
declare module 'react-beautiful-dnd/stories/src/horizontal/author-app.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/horizontal/author-app'>;
}
declare module 'react-beautiful-dnd/stories/src/horizontal/author-item.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/horizontal/author-item'>;
}
declare module 'react-beautiful-dnd/stories/src/horizontal/author-list.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/horizontal/author-list'>;
}
declare module 'react-beautiful-dnd/stories/src/horizontal/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/horizontal/types'>;
}
declare module 'react-beautiful-dnd/stories/src/primatives/quote-item.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/primatives/quote-item'>;
}
declare module 'react-beautiful-dnd/stories/src/reorder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/reorder'>;
}
declare module 'react-beautiful-dnd/stories/src/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/types'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical-grouped/quote-app.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical-grouped/quote-app'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical-nested/quote-app.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical-nested/quote-app'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical-nested/quote-list.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical-nested/quote-list'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical-nested/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical-nested/types'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical/quote-app.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical/quote-app'>;
}
declare module 'react-beautiful-dnd/stories/src/vertical/quote-list.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/stories/src/vertical/quote-list'>;
}
declare module 'react-beautiful-dnd/test/setup.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/setup'>;
}
declare module 'react-beautiful-dnd/test/unit/integration/hooks-integration.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/integration/hooks-integration.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/create-store.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/create-store.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/dimension.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/dimension.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/get-drag-impact.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/get-drag-impact.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/get-draggables-inside-droppable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/get-draggables-inside-droppable.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/get-droppable-over.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/get-droppable-over.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/get-new-home-client-offset.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/get-new-home-client-offset.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/hook-middleware.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/hook-middleware.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/jump-to-next-index.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/jump-to-next-index.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/state/position.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/state/position.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/connected-draggable-dimension-publisher.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/connected-draggable-dimension-publisher.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/connected-draggable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/connected-draggable.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/connected-droppable-dimension-publisher.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/connected-droppable-dimension-publisher.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/connected-droppable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/connected-droppable.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/drag-drop-context.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/drag-drop-context.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/drag-handle.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/drag-handle.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/moveable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/moveable.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/unconnected-draggable-dimension-publisher.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/unconnected-draggable-dimension-publisher.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/unconnected-draggable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/unconnected-draggable.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/unconnected-droppable-dimension-publisher.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/unconnected-droppable-dimension-publisher.spec'>;
}
declare module 'react-beautiful-dnd/test/unit/view/unconnected-droppable.spec.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/unit/view/unconnected-droppable.spec'>;
}
declare module 'react-beautiful-dnd/test/utils/get-client-rect.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/utils/get-client-rect'>;
}
declare module 'react-beautiful-dnd/test/utils/get-context-options.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/utils/get-context-options'>;
}
declare module 'react-beautiful-dnd/test/utils/set-window-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/utils/set-window-scroll'>;
}
declare module 'react-beautiful-dnd/test/utils/user-input-util.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/test/utils/user-input-util'>;
}
