// flow-typed signature: 1d23695e48901e3077b2176da77e8ea1
// flow-typed version: <<STUB>>/react-toggle-switch_v^2.1.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toggle-switch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toggle-switch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toggle-switch/dist/scripts/switch' {
  declare module.exports: any;
}

declare module 'react-toggle-switch/dist/scripts/switch.min' {
  declare module.exports: any;
}

declare module 'react-toggle-switch/example/app/scripts/main' {
  declare module.exports: any;
}

declare module 'react-toggle-switch/example/webpack.config.babel' {
  declare module.exports: any;
}

declare module 'react-toggle-switch/Gulpfile' {
  declare module.exports: any;
}

declare module 'react-toggle-switch/src/scripts/switch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toggle-switch/dist/scripts/switch.js' {
  declare module.exports: $Exports<'react-toggle-switch/dist/scripts/switch'>;
}
declare module 'react-toggle-switch/dist/scripts/switch.min.js' {
  declare module.exports: $Exports<'react-toggle-switch/dist/scripts/switch.min'>;
}
declare module 'react-toggle-switch/example/app/scripts/main.js' {
  declare module.exports: $Exports<'react-toggle-switch/example/app/scripts/main'>;
}
declare module 'react-toggle-switch/example/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-toggle-switch/example/webpack.config.babel'>;
}
declare module 'react-toggle-switch/Gulpfile.js' {
  declare module.exports: $Exports<'react-toggle-switch/Gulpfile'>;
}
declare module 'react-toggle-switch/src/scripts/switch.js' {
  declare module.exports: $Exports<'react-toggle-switch/src/scripts/switch'>;
}
