// flow-typed signature: 522d5e9f2f65109cae80784e91a66123
// flow-typed version: <<STUB>>/react-tag-input_v^4.7.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tag-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tag-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tag-input/dist-modules/ReactTags' {
  declare module.exports: any;
}

declare module 'react-tag-input/dist-modules/Suggestions' {
  declare module.exports: any;
}

declare module 'react-tag-input/dist-modules/Tag' {
  declare module.exports: any;
}

declare module 'react-tag-input/dist/ReactTags.min' {
  declare module.exports: any;
}

declare module 'react-tag-input/example/main' {
  declare module.exports: any;
}

declare module 'react-tag-input/example/vendor/JSXTransformer' {
  declare module.exports: any;
}

declare module 'react-tag-input/example/vendor/ReactDND.min' {
  declare module.exports: any;
}

declare module 'react-tag-input/lib/ReactTags' {
  declare module.exports: any;
}

declare module 'react-tag-input/lib/Suggestions' {
  declare module.exports: any;
}

declare module 'react-tag-input/lib/Tag' {
  declare module.exports: any;
}

declare module 'react-tag-input/test/reactTags.test' {
  declare module.exports: any;
}

declare module 'react-tag-input/test/suggestions.test' {
  declare module.exports: any;
}

declare module 'react-tag-input/test/tag.test' {
  declare module.exports: any;
}

declare module 'react-tag-input/webpack-dev-server.config' {
  declare module.exports: any;
}

declare module 'react-tag-input/webpack-production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tag-input/dist-modules/ReactTags.js' {
  declare module.exports: $Exports<'react-tag-input/dist-modules/ReactTags'>;
}
declare module 'react-tag-input/dist-modules/Suggestions.js' {
  declare module.exports: $Exports<'react-tag-input/dist-modules/Suggestions'>;
}
declare module 'react-tag-input/dist-modules/Tag.js' {
  declare module.exports: $Exports<'react-tag-input/dist-modules/Tag'>;
}
declare module 'react-tag-input/dist/ReactTags.min.js' {
  declare module.exports: $Exports<'react-tag-input/dist/ReactTags.min'>;
}
declare module 'react-tag-input/example/main.js' {
  declare module.exports: $Exports<'react-tag-input/example/main'>;
}
declare module 'react-tag-input/example/vendor/JSXTransformer.js' {
  declare module.exports: $Exports<'react-tag-input/example/vendor/JSXTransformer'>;
}
declare module 'react-tag-input/example/vendor/ReactDND.min.js' {
  declare module.exports: $Exports<'react-tag-input/example/vendor/ReactDND.min'>;
}
declare module 'react-tag-input/lib/ReactTags.js' {
  declare module.exports: $Exports<'react-tag-input/lib/ReactTags'>;
}
declare module 'react-tag-input/lib/Suggestions.js' {
  declare module.exports: $Exports<'react-tag-input/lib/Suggestions'>;
}
declare module 'react-tag-input/lib/Tag.js' {
  declare module.exports: $Exports<'react-tag-input/lib/Tag'>;
}
declare module 'react-tag-input/test/reactTags.test.js' {
  declare module.exports: $Exports<'react-tag-input/test/reactTags.test'>;
}
declare module 'react-tag-input/test/suggestions.test.js' {
  declare module.exports: $Exports<'react-tag-input/test/suggestions.test'>;
}
declare module 'react-tag-input/test/tag.test.js' {
  declare module.exports: $Exports<'react-tag-input/test/tag.test'>;
}
declare module 'react-tag-input/webpack-dev-server.config.js' {
  declare module.exports: $Exports<'react-tag-input/webpack-dev-server.config'>;
}
declare module 'react-tag-input/webpack-production.config.js' {
  declare module.exports: $Exports<'react-tag-input/webpack-production.config'>;
}
